src/Entity/Event.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass="App\Repository\EventRepository")
 */
class Event
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $location;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_participants;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Sport", inversedBy="events")
     * @ORM\JoinColumn(nullable=false)
     */
    private $sport;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getNbParticipants(): ?int
    {
        return $this->nb_participants;
    }

    public function setNbParticipants(int $nb_participants): self
    {
        $this->nb_participants = $nb_participants;

        return $this;
    }

    public function getSport(): ?Sport
    {
        return $this->sport;
    }

    public function setSport(?Sport $sport): self
    {
        $this->sport = $sport;

        return $this;
    }
}

src/Controller/AgendaController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\EventType;
use App\Repository\EventRepository;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AgendaController extends AbstractController
{
    /**
     * Affiche la page d'accueil et la liste des évènements
     * 
     * @Route("/", name="events")
     *
     * @param EventRepository $repo
     * @param Request $request
     * @param ObjectManager $manager
     * @return Response
     */
    public function index(EventRepository $repo, Request $request, ObjectManager $manager): Response
    {
        $events = $repo->findAll();

        $newEvent = new Event();
        $form = $this->createForm(EventType::class, $newEvent);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $manager->persist($newEvent);
            $manager->flush();
            $this->addFlash(
                'success',
                "L'énèvement a bien été ajouté"
            );
        }

        return $this->render('agenda/index.html.twig', [
            'events' => $events,
            'form' => $form->createView()
        ]);
    }

    /**
     * Affiche un évènement
     * 
     * @Route("/event/{id}", name="event_single")
     *
     * @param Event $event
     * @param Request $request
     * @param ObjectManager $manager
     * @return Response
     */
    public function show(Event $event, Request $request, ObjectManager $manager): Response
    {
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $manager->persist($event);
            $manager->flush();
            $this->addFlash(
                'success',
                "L'énèvement a bien été mis à jour"
            );
        }

        return $this->render('agenda/show.html.twig', [
            'event' => $event,
            'form' => $form->createView()
        ]);
    }

    /**
     * Supprime un évènement
     * 
     * @Route("/event/delete/{id}", name="event_delete")
     *
     * @param Event $event
     * @param ObjectManager $manager
     * @return Response
     */
    public function delete(Event $event, ObjectManager $manager): Response
    {
        $manager->remove($event);
        $manager->flush();
        $this->addFlash(
            'success',
            "La page <strong>{$event->getName()}</strong> a bien été supprimée"
        );

        return $this->redirectToRoute("events");
    }
}

templates/agenda/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Calendrier{% endblock %}

{% block body %}
    <div class="container my-5">
        <div class="row">
            {% for event in events %}
                <div class="col-4 my-3 d-flex justify-content-center fade-in">
                    <div class="card" style="width: 18rem;">
                        <div class="hover-img">
                            <img src="http://placehold.it/340x200" class="card-img-top" alt="{{ event.name }}">
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">{{ event.name }}</h5>
                            <p class="card-text">
                                le {{ event.date | date('d/m/Y') }} à {{ event.location }}
                            </p>
                            <a href="{{ path('event_single', {'id': event.id}) }}" class="btn btn-primary">Voir</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    {% if is_granted('ROLE_ADMIN') %}
        <div class="addButton">
            <a href="#" data-toggle="modal" data-target="#add_event" class="addButtonLink bg-primary text-light p-3"><i class="fas fa-plus"></i></a>
        </div>
        <div class="modal fade" id="add_event" tabindex="-1" role="dialog" aria-labelledby="add_eventLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="add_eventLabel">Nouvel évènement</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {{ form_start(form) }}
                        <div class="modal-body">
                            {{ form_widget(form) }}
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Annuler</button>
                            <button type="submit" class="btn btn-success">Publier</button>
                        </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/agenda/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ event.name }}{% endblock %}

{% block body %}
    <div class="container my-5">
        <div class="row">
            <div class="col-4 my-3 fade-in">
                <img src="http://placehold.it/340x200" class="card-img-top" alt="{{ event.name }}">
                {% if is_granted('ROLE_ADMIN') %}
                    <div class="row">
                        <button data-toggle="modal" data-target="#edit_event" class="btn btn-primary mt-3 ml-3">Modifier</button>
                        <a href="{{ path('event_delete', {'id': event.id }) }}" class="btn btn-outline-danger mt-3 ml-3" onclick="return confirm(`Êtes vous sûr de vouloir supprimer l'évènement ?`)">Supprimer</a>
                    </div>
                {% endif %}
            </div>
            <div class="col-8 fade-right">
                <h1 class="pt-1">{{ event.name }}</h1>
                <p class="font-italic">le {{ event.date | date('d/m/Y') }} à {{ event.location }}</p>
                <p>Nombre de participants maximum : {{ event.nbParticipants }}</p>
                <p>Sport : {{ event.sport.name }}</p>
            </div>
        </div>
    </div>
    {% if is_granted('ROLE_ADMIN') %}
        <div class="modal fade" id="edit_event" tabindex="-1" role="dialog" aria-labelledby="edit_eventLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="edit_eventLabel">Nouvel évènement</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {{ form_start(form) }}
                        <div class="modal-body">
                            {{ form_widget(form) }}
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Annuler</button>
                            <button type="submit" class="btn btn-success">Mettre à jour</button>
                        </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}